### ISSUE TITLE
InvoiceNumber wird nicht richtig generiert, headText

### ISSUE THREAD

**Issue by Fernien** [exlo89/laravel-sevdesk-api#16]
Hi, 
habe aktuell das Problem, dass die Rechnungsnummern nicht mehr richtig generiert werden.
Wenn ich in den parametern invoiceNumber => null übergebe erhalte ich diese Rechnungsnummer: RE-%YYYY%MM1038

Jahr und Monat werden nicht richtig gesetzt. headText und footText werden auch nicht übernommen, könnte aber vielleicht folgefehler sein.

Hat jemand ne Idee?

**Comment by Fernien** [comment]
Wird hier nicht sogar der falsche Key geprüft und überschrieben?
<img width="577" alt="image" src="https://github.com/exlo89/laravel-sevdesk-api/assets/28627530/934915b6-2d5a-4ac0-8b9a-051acd18ef93">
Müsste das nicht wie von mir markiert $parameters['invoice']['invoiceNumber'] statts $parameters['invoiceNumber'] sein?
Laut SevDesk Doku gehört invoiceNumber unterhalb des invoice keys siehe:
![image](https://github.com/exlo89/laravel-sevdesk-api/assets/28627530/0cf3a374-3939-42fb-ac19-726b86188af1)

**Comment by exlo89** [comment]
Welche version hast du denn aktuell installiert?

**Comment by Fernien** [comment]
Ups, ganz vergessen. exlo89/laravel-sevdesk-api          dev-main 90239bb

Bin etwas irritiert, weil es vorher so funktioniert hatte. Mir ist kein commit aufgefallen der etwas geändert hätte

**Comment by Fernien** [comment]
@exlo89 Können wir nicht einfach invoiceNumber = null schicken? Dann dürfte SevDesk das ja komplett ausfüllen

**Comment by exlo89** [comment]
Wenn man null zu Sevdesk schickt, dann generiert dir Sevdesk nicht die invoice number. Deswegen habe ich mich ja damals dafür entschieden, dass es gleich mit generiert wird.

**Comment by exlo89** [comment]
seit wann tritt denn der Fehler auf?

**Comment by Fernien** [comment]
> Wenn man null zu Sevdesk schickt, dann generiert dir Sevdesk nicht die invoice number. Deswegen habe ich mich ja damals dafür entschieden, dass es gleich mit generiert wird.

Ich glaub das haben die geändert. Hab noch ein Python Script wo ich deren API nutze und wenn ich null übergebe generiert er das richtig

**Comment by Fernien** [comment]
> seit wann tritt denn der Fehler auf?

Kann's nicht genau sagen. Ich generiere darüber aktuell nur einmal im Monat Rechnungen. Letzten Monat ging es noch. Am 1.3 ist mir es aufgefallen

**Comment by Fernien** [comment]
@exlo89 problem besteht weiterhin.
Das Rechnungsdatum wird nicht korrekt generiert. Die generierte rechnung sieht dann so "RE-%YYYY%MM0001" Statts "RE-2024040001"

**Comment by Fernien** [comment]
Das auszukommentieren hilft prinzipiell in meinem Fall, allerdings weiß ich nicht wo und wie es noch woanders genutzt wird.
Wenn die Felder null sind füllt SevDesk den Rest aus
![image](https://github.com/exlo89/laravel-sevdesk-api/assets/28627530/689ef86e-8620-4d48-97fa-5159e62c6eaf)

**Comment by exlo89** [comment]
Ich glaub ich weiß was du jetzt meinst. Also wenn die Rechnung erstellt werden mit den "OPEN" Status, dann werden die InvoiceNumber erstellt. Laut Dokumentation wird aber die nächste Rechnungsnummer nicht über die Rechnung erstellt, sondern über einen eigenen API Endpoint. Ich werd diesen Entpoint mit hinzufügen um die nächsten Rechnungsnummern zu generieren.

**Comment by exlo89** [comment]
Hab ein neues Update erstellt. Es gibt jetzt getSequence() enpoints um die aktuelle Nummer zu bekommen von einer Rechnung oder einer Gutschrift. Die Formate mit Datum werden aber nicht mit ausgegeben.

**Comment by Fernien** [comment]
Hab ganz vergessen nochmal Feedback zu geben. Hat alles funktioniert
