### ISSUE TITLE
Angebote

### ISSUE THREAD

**Issue by Alphaverse** [exlo89/laravel-sevdesk-api#20]
Guten Tag,

die Möglichkeit zur Erstellung von Angeboten über die Bereitgestellte API wäre tatsächlich noch sehr hilfreich.

Gibt es diese Möglichkeit schon oder wäre es möglich dies zu implementieren?

**Comment by exlo89** [comment]
Hallo @Alphaverse ich schau mal was ich die Tage implementieren kann. :)

**Comment by exlo89** [comment]
@Alphaverse das update ist fertig und mit version 1.0 ist es jetzt möglich auch order zu erstellen :)
