### ISSUE TITLE
Return values as collections

### ISSUE THREAD

**Issue by ghost** [exlo89/laravel-sevdesk-api#3]
My Idea is that the return values of some functions should be Collections instead of regular arrays.
This adds some more functionality to them and integrates it better into Laravel.

Example:

``` php
// In Class Exlo89\LaravelSevdeskApi\Api\Contact;
    public function all(int $depth = 0)
    {
        // Only difference is the Collection::make()
        return Collection::make($this->_get(Routes::CONTACT, ['depth' => $depth]));
    }
```

``` php
$sevdeskapi = Sevdesk::make();
$contacts = $sevdeskApi->contact()->all()
$contacts->first() // now possible since it is a collection
```

Maybe there is a smoother way to achive this.

**Comment by exlo89** [comment]
@sebitwo that is a good idea. give me some time to implement it. :)

**Comment by ghost** [comment]
I opened a pull request that implements it the way i suggested ^^ But as i said: this may not be the best way to do it /s

**Comment by exlo89** [comment]
nice work :)
