### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Sebbito** [exlo89/laravel-sevdesk-api#6]
Right now it's not really clear what parts of the API are covered and which ones aren't.
The Readme is a good start but perhaps there should be something more complete.
Maybe there are some tools to automatically generate docs?

**Comment by exlo89** [comment]
Currently, I add what I also program. But in a long time, you are right to generate all the docs. Did you have some recommendations on how to do that?

**Comment by Sebbito** [comment]
Nope I don't know about any automatic solutions. Maybe I'll find something.

**Comment by Sebbito** [comment]
I found [phpdoc](https://docs.phpdoc.org/3.0/guide/getting-started/installing.html#stand-alone-using-docker)
But as far as i can see it, that only automatically generates documentation in the form of html sites. Seems a little impractical.

**Comment by Sebbito** [comment]
Perhaps the Wiki Tab here on Github is good enough? Put the very basics into the README and the more fine-grained information into dedicated wiki pages.
